site_name: GCP Guide | The Narit Lab
site_url: https://thenaritlab.github.io/gcp/
repo_url: https://github.com/thenaritlab/gcp
copyright: Created by The Narit Lab

theme:
  name: material
  language: th
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      toggle: { icon: material/weather-night, name: Dark mode }
    - scheme: slate
      toggle: { icon: material/weather-sunny, name: Light mode }

markdown_extensions:
  - github-callouts
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - หน้าแรก: index.md
  - BigQuery เบื้องต้น: bigquery-basics.md
